const Exemple_data = [
    {
        id: 1,
        category: "Sublimation",
        totalLike: "11",
        title: "MUG OURS Toulouse",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
    {
        id: 2,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la mdlddpd",
    },
    {
        id: 3,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
    {
        id: 4,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
    {
        id: 5,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
    {
        id: 6,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
    {
        id: 7,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
    {
        id: 8,
        category: "BLABLA",
        totalLike: "11",
        title: "Broderie",
        image: "./image/mugours.jpg",
        description: "Sublimation pour la marque OURS TOULOUSE",
    },
]

export default Exemple_data